#
#	Sections
#

general:
  title: General Settings
  type: section

advanced:
  title: Advanced Settings
  type: section

#
# Settings
#

enabled:
  title: Enable Protection
  type: checkbox
  default: on

password:
  title: Password
  type: password
  default: password

login_duration:
  title: How long before a user's session expires
  type: text
  default: 86400 # one day
  section: advanced

enable_public_rss_feeds:
  title: Make RSS feeds publicly viewable
  type: checkbox
  default: off
  section: advanced