#
#	settings.yaml contains the setting definitions in a nice human-readable format
#

enabled:
  type: checkbox
  default: on
  section_title: General Settings

password:
  type: password
  default: password

login_duration:
  type: text
  default: 86400 #one day
  section: advanced
  section_title: Advanced Settings